use sql_challenge;

--1.Question: Find products sold in the highest quantity.
select od.product_id, p.product_name, SUM(od.quantity) as total_quantity_sold
from clean_order_details od
join clean_products p on od.product_id = p.product_id
group by od.product_id, p.product_name
order by total_quantity_sold desc
limit 5;

--2.Question: Find the least selling products.
select od.product_id, p.product_name, SUM(od.quantity) as total_quantity_sold
from clean_order_details od
join clean_products p on od.product_id = p.product_id
group by od.product_id, p.product_name
order by total_quantity_sold asc
limit 5;

--3.Question: Find revenue generated by each product.
select od.product_id, p.product_name, SUM(od.quantity * p.price) as revenue
from clean_products p
join clean_order_details od on p.product_id = od.product_id
group by od.product_id, p.product_name
order by revenue desc;

--4.Question: Find total sales for each category.
select p.category, SUM(p.price * od.quantity) as category_sales
from clean_products p
join clean_order_details od on od.product_id = p.product_id
group by p.category
order by category_sales desc;

--5.Question: Find the highest priced product that was sold.
select distinct p.product_id, p.product_name, p.price
from clean_products p
join clean_order_details od on p.product_id = od.product_id
order by p.price DESC
limit 5;

--6.Question: Find average product price category-wise.
select category , AVG(price) as avg_price
from clean_products
group by category
order by avg_price desc;

--7.Question: Find daily quantity sold for each product.
select p.product_name, o.order_date, sum(od.quantity) as total_quantity
from clean_products p
join clean_order_details od on  p.product_id = od.product_id
join clean_orders o on od.order_id = o.order_id
group by p.product_name, o.order_date
order by o.order_date; 