use sql_challenge;

--1.Question: Find total business revenue.
select sum(payment_amount) as total_revenue
from clean_payments;

--2.Question: Find daily revenue.
select payment_date, SUM(payment_amount) as daily_revenue
from clean_payments
group by payment_date
order by payment_date;

--3.Question: Find monthly revenue trend.
select MONTHNAME(payment_date) as month_name, MONTH(payment_date) as month_no, SUM(payment_amount) as monthly_revenue
from clean_payments
group by MONTH(payment_date), MONTHNAME(payment_date)
order by MONTH(payment_date);

--4.Question: Find revenue generated by each product.
select od.product_id, p.product_name, SUM(od.quantity * p.price) as productwise_revenue
from clean_order_details od 
join clean_products p on od.product_id = p.product_id
group by od.product_id, p.product_name
order by productwise_revenue desc;

--5.Question: Find customer-wise revenue.
select c.customer_name, o.customer_id, SUM(p.payment_amount) as customerwise_revenue
from clean_customers c
join clean_orders o on c.customer_id = o.customer_id
join clean_payments p on o.order_id = p.order_id
group by c.customer_name, o.customer_id
order by customerwise_revenue desc;

--6.Question: Find category-wise revenue.
select p.category, SUM(od.quantity * p.price) as categorywise_revenue
from clean_order_details od 
join clean_products p on od.product_id = p.product_id
group by p.category
order by categorywise_revenue;

--7.Question: Find days generating highest revenue.
select payment_date, sum(payment_amount) as total_revenue
from clean_payments
group by payment_date
order by total_revenue desc;



